/**
 * 内部精简离线小词典包 (分离出来供备用)
 */
const translationDict = {
    'hello': '你好', 'world': '世界', 'phonetics': '语音学', 'translation': '翻译',
    'a': '一个', 'abandon': '放弃', 'ability': '能力', 'able': '能够的',
    'about': '关于', 'above': '上面', 'accept': '接受', 'across': '穿过',
    'act': '行动', 'action': '行动', 'actually': '实际上', 'add': '添加',
    'address': '地址', 'after': '之后', 'again': '再次', 'against': '反对',
    'age': '年龄', 'ago': '以前', 'agree': '同意', 'air': '空气',
    'all': '所有', 'allow': '允许', 'almost': '几乎', 'along': '沿着',
    'already': '已经', 'also': '也', 'always': '总是', 'among': '在...中',
    'an': '一个', 'and': '和', 'animal': '动物', 'another': '另一个',
    'answer': '回答', 'any': '任何', 'anyone': '任何人', 'anything': '任何事',
    'appear': '出现', 'apple': '苹果', 'area': '区域', 'arm': '手臂',
    'around': '周围', 'art': '艺术', 'as': '作为', 'ask': '问',
    'at': '在', 'attention': '注意', 'away': '远离',
    'back': '回来', 'bad': '坏的', 'ball': '球', 'bank': '银行',
    'be': '是', 'beautiful': '美丽的', 'because': '因为', 'become': '成为',
    'bed': '床', 'before': '之前', 'begin': '开始', 'behind': '后面',
    'believe': '相信', 'best': '最好的', 'better': '更好的', 'between': '之间',
    'big': '大的', 'black': '黑色的', 'blue': '蓝色的', 'body': '身体',
    'book': '书', 'both': '两个都', 'boy': '男孩', 'break': '打破',
    'bring': '带来', 'brother': '兄弟', 'brown': '棕色的', 'build': '建造',
    'building': '建筑', 'business': '商业', 'but': '但是', 'buy': '买',
    'by': '通过', 'call': '叫', 'camera': '相机', 'can': '能',
    'car': '汽车', 'card': '卡片', 'care': '关心', 'carry': '携带',
    'case': '情况', 'cat': '猫', 'catch': '抓住', 'cause': '原因',
    'change': '改变', 'child': '孩子', 'children': '孩子们', 'choice': '选择',
    'city': '城市', 'class': '班级', 'clear': '清楚的', 'close': '关闭',
    'cold': '冷的', 'color': '颜色', 'come': '来', 'common': '共同的',
    'community': '社区', 'company': '公司', 'companion': '伙伴', 'computer': '电脑',
    'continue': '继续', 'control': '控制', 'cost': '花费', 'could': '可以',
    'country': '国家', 'course': '课程', 'create': '创造', 'cup': '杯子',
    'cut': '切', 'dark': '黑暗的', 'daughter': '女儿', 'day': '天',
    'dead': '死的', 'deal': '交易', 'deep': '深的', 'design': '设计',
    'develop': '发展', 'die': '死', 'different': '不同的', 'difficult': '困难的',
    'do': '做', 'doctor': '医生', 'dog': '狗', 'door': '门',
    'down': '下', 'draw': '画', 'dream': '梦想', 'drive': '驾驶',
    'during': '在...期间', 'each': '每个', 'early': '早的', 'earth': '地球',
    'east': '东方', 'easy': '容易的', 'eat': '吃', 'education': '教育',
    'effect': '效果', 'eight': '八', 'end': '结束', 'energy': '能量',
    'english': '英语', 'enjoy': '享受', 'enough': '足够', 'enter': '进入',
    'environment': '环境', 'even': '甚至', 'evening': '晚上', 'ever': '曾经',
    'every': '每个', 'everyone': '每个人', 'everything': '一切', 'example': '例子',
    'experience': '经验', 'explain': '解释', 'eye': '眼睛',
    'face': '脸', 'fact': '事实', 'fall': '落下', 'family': '家庭',
    'far': '远的', 'fast': '快的', 'father': '父亲', 'feel': '感觉',
    'few': '少数', 'field': '领域', 'fight': '战斗', 'fill': '填充',
    'film': '电影', 'final': '最终的', 'finally': '最终', 'find': '找到',
    'fine': '好的', 'finish': '完成', 'fire': '火', 'first': '第一',
    'fish': '鱼', 'five': '五', 'floor': '地板', 'fly': '飞',
    'follow': '跟随', 'food': '食物', 'foot': '脚', 'for': '为了',
    'force': '力量', 'foreign': '外国的', 'forget': '忘记', 'form': '形式',
    'four': '四', 'fox': '狐狸', 'free': '自由的', 'friend': '朋友',
    'from': '从', 'front': '前面', 'full': '满的', 'future': '未来',
    'game': '游戏', 'garden': '花园', 'get': '得到', 'girl': '女孩',
    'give': '给', 'glass': '玻璃', 'go': '去', 'god': '上帝',
    'good': '好的', 'government': '政府', 'great': '伟大的', 'green': '绿色的',
    'ground': '地面', 'group': '团体', 'grow': '成长', 'guess': '猜测',
    'guy': '家伙', 'hair': '头发', 'half': '一半', 'hand': '手',
    'happen': '发生', 'happy': '快乐的', 'hard': '困难的', 'have': '有',
    'he': '他', 'head': '头', 'health': '健康', 'hear': '听到',
    'heart': '心', 'hello': '你好', 'help': '帮助', 'her': '她的',
    'here': '这里', 'high': '高的', 'him': '他', 'his': '他的',
    'history': '历史', 'hold': '持有', 'home': '家', 'hope': '希望',
    'hot': '热的', 'house': '房子', 'how': '怎样', 'however': '然而',
    'human': '人类', 'hundred': '百', 'husband': '丈夫',
    'i': '我', 'idea': '想法', 'if': '如果', 'image': '图像',
    'important': '重要的', 'improve': '改进', 'in': '在...里', 'include': '包括',
    'increase': '增加', 'information': '信息', 'inside': '里面', 'instead': '代替',
    'interest': '兴趣', 'interesting': '有趣的', 'into': '进入', 'is': '是',
    'it': '它', 'job': '工作', 'join': '加入', 'jumps': '跳跃',
    'just': '只是', 'keep': '保持', 'key': '关键', 'kid': '孩子',
    'kind': '种类', 'know': '知道', 'knowledge': '知识',
    'land': '土地', 'language': '语言', 'large': '大的', 'last': '最后的',
    'late': '晚的', 'later': '后来', 'laugh': '笑', 'law': '法律',
    'lazy': '懒惰的', 'lead': '领导', 'learn': '学习', 'leave': '离开',
    'left': '左边', 'less': '更少', 'let': '让', 'letter': '信',
    'level': '水平', 'life': '生活', 'light': '光', 'like': '喜欢',
    'line': '线', 'list': '列表', 'listen': '听', 'little': '小的',
    'live': '住', 'long': '长的', 'look': '看', 'lose': '失去',
    'lot': '很多', 'love': '爱', 'low': '低的',
    'make': '制作', 'man': '男人', 'many': '许多', 'market': '市场',
    'may': '可以', 'me': '我', 'mean': '意思', 'meet': '遇见',
    'meeting': '会议', 'member': '成员', 'memory': '记忆', 'menu': '菜单',
    'message': '消息', 'mind': '心智', 'minute': '分钟', 'model': '模型',
    'modern': '现代的', 'moment': '时刻', 'money': '钱', 'month': '月',
    'more': '更多', 'morning': '早上', 'most': '最多', 'mother': '母亲',
    'move': '移动', 'movie': '电影', 'much': '许多', 'music': '音乐',
    'must': '必须', 'my': '我的', 'name': '名字', 'nation': '国家',
    'natural': '自然的', 'nature': '自然', 'near': '近的', 'need': '需要',
    'never': '从不', 'new': '新的', 'news': '新闻', 'next': '下一个',
    'nice': '好的', 'night': '夜晚', 'no': '不', 'not': '不',
    'note': '笔记', 'nothing': '没有什么', 'now': '现在', 'number': '数字',
    'of': '的', 'off': '离开', 'offer': '提供', 'office': '办公室',
    'often': '经常', 'old': '老的', 'on': '在...上', 'once': '一次',
    'one': '一', 'only': '只有', 'open': '打开', 'or': '或者',
    'order': '命令', 'other': '其他的', 'our': '我们的', 'out': '外面',
    'over': '超过', 'own': '自己的',
    'page': '页面', 'paper': '纸', 'parent': '父母', 'part': '部分',
    'party': '聚会', 'pass': '通过', 'past': '过去', 'pay': '付款',
    'peace': '和平', 'people': '人们', 'person': '人', 'phone': '电话',
    'photo': '照片', 'picture': '图片', 'place': '地方',
    'plan': '计划', 'play': '玩', 'please': '请', 'point': '点',
    'poor': '贫穷的', 'popular': '流行的', 'position': '位置', 'possible': '可能的',
    'power': '权力', 'practice': '练习', 'present': '现在', 'president': '总统',
    'price': '价格', 'problem': '问题', 'process': '过程', 'produce': '生产',
    'product': '产品', 'program': '程序', 'project': '项目', 'provide': '提供',
    'public': '公共的', 'put': '放',
    'quality': '质量', 'question': '问题', 'quick': '快的', 'quickly': '快速地',
    'quite': '相当',
    'read': '读', 'reading': '阅读', 'ready': '准备', 'real': '真实的',
    'really': '真的', 'reason': '原因', 'receive': '接收', 'red': '红色的',
    'remember': '记住', 'report': '报告', 'require': '需要', 'research': '研究',
    'rest': '休息', 'restaurant': '餐厅', 'result': '结果', 'return': '返回',
    'right': '正确的', 'rise': '上升', 'road': '道路', 'room': '房间',
    'rule': '规则', 'run': '跑',
    'safe': '安全的', 'same': '相同的', 'save': '保存', 'say': '说',
    'school': '学校', 'science': '科学', 'sea': '海', 'see': '看见',
    'seem': '似乎', 'send': '发送', 'service': '服务', 'set': '设置',
    'she': '她', 'short': '短的', 'should': '应该', 'show': '展示',
    'side': '边', 'simple': '简单的', 'since': '自从', 'sister': '姐妹',
    'sit': '坐', 'six': '六', 'small': '小的', 'so': '所以',
    'some': '一些', 'someone': '某人', 'something': '某事', 'sometimes': '有时',
    'son': '儿子', 'song': '歌曲', 'soon': '不久', 'sound': '声音',
    'speak': '说话', 'special': '特别的', 'stand': '站立', 'start': '开始',
    'state': '状态', 'stay': '停留', 'still': '仍然', 'stop': '停止',
    'story': '故事', 'street': '街道', 'strong': '强壮的', 'student': '学生',
    'study': '学习', 'such': '如此', 'support': '支持', 'sure': '确定',
    'system': '系统',
    'table': '桌子', 'take': '拿', 'talk': '谈话', 'teacher': '老师',
    'team': '团队', 'tell': '告诉', 'ten': '十', 'test': '测试',
    'than': '比', 'thank': '谢谢', 'that': '那个', 'the': '这个',
    'their': '他们的', 'them': '他们', 'then': '然后', 'there': '那里',
    'these': '这些', 'they': '他们', 'thing': '事物', 'think': '想',
    'this': '这个', 'those': '那些', 'though': '虽然', 'thought': '想法',
    'three': '三', 'through': '通过', 'time': '时间', 'to': '到',
    'today': '今天', 'together': '一起', 'too': '也', 'top': '顶部',
    'total': '总共', 'town': '城镇', 'travel': '旅行',
    'tree': '树', 'true': '真的', 'try': '尝试', 'turn': '转',
    'two': '二', 'type': '类型',
    'under': '在...下', 'understand': '理解', 'until': '直到', 'up': '上',
    'us': '我们', 'use': '使用', 'usually': '通常',
    'value': '价值', 'very': '非常', 'view': '视图', 'visit': '访问',
    'voice': '声音', 'wait': '等待', 'walk': '走', 'wall': '墙',
    'want': '想要', 'war': '战争', 'watch': '看', 'water': '水',
    'way': '方式', 'we': '我们', 'week': '周', 'welcome': '欢迎',
    'well': '好', 'west': '西方', 'what': '什么', 'when': '当...时',
    'where': '哪里', 'which': '哪个', 'while': '当...时', 'white': '白色的',
    'who': '谁', 'whole': '整个', 'why': '为什么', 'wife': '妻子',
    'will': '将', 'win': '赢', 'window': '窗户', 'with': '和',
    'without': '没有', 'woman': '女人', 'word': '单词', 'work': '工作',
    'world': '世界', 'worry': '担心', 'would': '将会', 'write': '写',
    'wrong': '错误的', 'year': '年', 'yes': '是', 'yet': '然而',
    'you': '你', 'young': '年轻的', 'your': '你的'
}

module.exports = {
    translationDict
}
